language: java

install: ant deps

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk6

script:
    - "PressDemo.java"
    
script:
  - jdk_switcher use oraclejdk8
  - # do stuff with Java 8
  - jdk_switcher use oraclejdk7
  - # do stuff with Java 7

after_failure:
    - email
